### PR TITLE
CommentsAdapter

### PR DESCRIPTION
**Pull request by ZeRoGerc**
- New adapter for comments
 - FullPostInfoActivity now does't show comments and likes. Need complete refactoring
 - FullPostInfoActivity will be fixed in next request

### CODE REVIEW

**Comment by danilkolikov** [comment]
I think it's better to fix adapter and then make request

**Comment by ZeRoGerc** [comment]
Adapter is fine

**Comment by danilkolikov** [comment]
I meant activity. You said that it will be fixed later, why not to fix it in this request?

**Comment by ZeRoGerc** [comment]
Cause it envolves full refactoring and rewriting

**Comment by danilkolikov** [comment]
Anyway you will do it. I think, if you do refactor, it won't clash with my changes, because they will be in different parts of project

**Comment by ZeRoGerc** [comment]
ok, then another commit is coming)

**Comment by danilkolikov** [comment]
Much better

**Pull request merged**
